### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by holtkamp**

### CODE REVIEW

**Comment by holtkamp** [comment]
@akshayraje
@abhayks1

Is anyone monitoring this repository?

**Comment by akshayraje** [comment]
Hey @holtkamp sorry for the delay on this. We'll review this and merge soon.

**Review by akshayraje — APPROVED** [review]

**Comment by holtkamp** [comment]
@akshayraje thanks, is the API Client still under development? I might be able to submit some more Pull Requests to increase the quality / strictness

**Comment by holtkamp** [comment]
@akshayraje it has been almost a month since my question: https://github.com/pepotech/pepocampaigns-php/pull/1#issuecomment-665020677

Is PepoCampaigns still under development / active support? Also found some bugs in the GUI, would love to report them, but I need to be sure whether it will receive attention from the company behind it...

**Comment by akshayraje** [comment]
@abhayks1 can you please help @holtkamp

**Comment by holtkamp** [comment]
@akshayraje
@abhayks1

Where should issues with the GUI be reported?

**Pull request merged**
